message: deploy-chroma
service:
  expose: "8000"
  autoscaling:
    min: 1
    max: 2
    metric: cpu
    target: 50
resources:
  cluster: vessl-aws-seoul
  preset: cpu-medium-spot
image: python:3.11.9
import:
  /app/:
    git:
      url: github.com/vessl-ai/knowledge-manager.git
      ref: main
      credential_name: vessl-ai
run:
  - command: "apt update && apt install apache2-utils\npip install poetry\npoetry install \npoetry run ./prepare-auth.sh\npoetry run ./launch-chroma.sh\n"
    workdir: /app/services/deploy-chroma
ports:
  - 8000
env:
  CHROMA_SERVER_AUTHN_PASSWORD: password
  CHROMA_SERVER_AUTHN_USERNAME: user
